ConnectionStrings:
  Default: Server=localhost;Database=AsynchronousBackgroundProcessing;User Id=sa;Password=Passw0rd(!);MultipleActiveResultSets=true

# My Jobs
MyJobs:
  - JobCode: FirstJob
    JobName: First Job
    CronExpression: "* * * * *"
    Enabled: true
    
  - JobCode: SecondJob
    JobName: Second Job
    CronExpression: "* * * * *"
    Enabled: true

  - JobCode: ThirdJob
    JobName: Third Job
    CronExpression: "* * * * *"
    Enabled: true